/* generated by l1trans from mixa_manager/mixa_process.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fprocess_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fprocess_2Eh_2Elm1

#include <stddef.h>
#define MIXA_PROC_OK 0
#define MIXA_PROC_ERR_ARG 1
#define MIXA_PROC_ERR_SPAWN 2
#define MIXA_PROC_ERR_IO 3
#define MIXA_PROC_ERR_NOMEM 4
#define MIXA_PROC_EOF 5
typedef struct MixaProcess MixaProcess;

int mixa_process_spawn(MixaProcess ** out, const char * command_line_utf8, const char * cwd_utf8, int stdin_enabled);
int mixa_process_read(MixaProcess * p, void * buf, size_t cap, size_t * got);
int mixa_process_write(MixaProcess * p, const void * buf, size_t n, size_t * wrote);
int mixa_process_status(MixaProcess * p, int * running, int * exit_code);
int mixa_process_kill(MixaProcess * p);
void mixa_process_close(MixaProcess ** p);
#endif
