/* generated by l1trans from mixa_manager/mixa_app_path.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fapp_5Fpath_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fapp_5Fpath_2Eh_2Elm1

#include <stddef.h>
#define MIXA_APP_PATH_OK 0
#define MIXA_APP_PATH_ERR_ARG 1
#define MIXA_APP_PATH_ERR_NOMEM 2
#define MIXA_APP_PATH_ERR_OVERFLOW 3
typedef struct MixaAppPathFaultVTable MixaAppPathFaultVTable;

typedef int (*MixaAppPathFaultFn)(void * ctx, size_t requested_size);

struct MixaAppPathFaultVTable {
    MixaAppPathFaultFn on_alloc;
    void * ctx;
};

int mixa_app_path_total(size_t a_len, size_t b_len, size_t * out_total);
int mixa_app_path_join(const char * a, const char * b, const MixaAppPathFaultVTable * fault, char ** out);
#endif
