/* generated by l1trans from mixa_manager/mixa_tiles.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Ftiles_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Ftiles_2Eh_2Elm1

#include <stddef.h>
#include "mixa_manager/mixa_core.lm1.h"
#include "mixa_manager/mixa_overlay.lm1.h"
#define MIXA_TILE_BASE 0xE000U
#define MIXA_TILE_LAST 0xE00FU
#define MIXA_TILE_GAP_L 0x1U
#define MIXA_TILE_GAP_R 0x2U
#define MIXA_TILE_GAP_T 0x4U
#define MIXA_TILE_GAP_B 0x8U
#define MIXA_TILE_FILL (MIXA_TILE_BASE)
#define MIXA_TILE_W (MIXA_TILE_BASE | MIXA_TILE_GAP_L)
#define MIXA_TILE_E (MIXA_TILE_BASE | MIXA_TILE_GAP_R)
#define MIXA_TILE_N (MIXA_TILE_BASE | MIXA_TILE_GAP_T)
#define MIXA_TILE_S (MIXA_TILE_BASE | MIXA_TILE_GAP_B)
#define MIXA_TILE_NW (MIXA_TILE_BASE | MIXA_TILE_GAP_L | MIXA_TILE_GAP_T)
#define MIXA_TILE_NE (MIXA_TILE_BASE | MIXA_TILE_GAP_R | MIXA_TILE_GAP_T)
#define MIXA_TILE_SW (MIXA_TILE_BASE | MIXA_TILE_GAP_L | MIXA_TILE_GAP_B)
#define MIXA_TILE_SE (MIXA_TILE_BASE | MIXA_TILE_GAP_R | MIXA_TILE_GAP_B)
#define MIXA_TILE_ALL (MIXA_TILE_BASE | MIXA_TILE_GAP_L | MIXA_TILE_GAP_R | MIXA_TILE_GAP_T | MIXA_TILE_GAP_B)

size_t mixa_tile_gap_px(size_t cell_h);
int mixa_tile_is(unsigned codepoint);
unsigned mixa_tile_gaps(unsigned codepoint);
unsigned mixa_tile_from_gaps(unsigned gaps);
int mixa_tile_pixel_solid(unsigned codepoint, size_t lx, size_t ly, size_t cell_w, size_t cell_h);
int mixa_tile_paint_cell(unsigned codepoint, unsigned bg, unsigned alpha, size_t cell_x, size_t cell_y, size_t cell_w, size_t cell_h, MixaU8 * out_rgba, size_t width, size_t height);
int mixa_tile_fill_button(MixaTextRect * rect, size_t row, size_t col, size_t nrows, size_t ncols, unsigned fg, unsigned bg, unsigned alpha);
#endif
