/* generated by l1trans from mixa_manager/mixa_cmdline_dispatch.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fcmdline_5Fdispatch_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fcmdline_5Fdispatch_2Eh_2Elm1

#include <stddef.h>
#include "mixa_manager/mixa_file.lm1.h"
#define MIXA_CMD_DISPATCH_OK 0
#define MIXA_CMD_DISPATCH_ERR_ARG 1
#define MIXA_CMD_DISPATCH_ERR_NOMEM 2
#define MIXA_CMD_DISPATCH_ERR_IO 3
#define MIXA_CMD_DISPATCH_ERR_SPAWN 4
#define MIXA_CMD_DISPATCH_RUNNING 0
#define MIXA_CMD_DISPATCH_DONE 1
typedef struct MixaCmdDispatch MixaCmdDispatch;

int mixa_cmd_dispatch_start(const char * command_utf8, const char * cwd_utf8, MixaFile * console_file, MixaCmdDispatch ** out);
int mixa_cmd_dispatch_poll(MixaCmdDispatch * d, int * out_exit_code, char ** out_new_cwd);
int mixa_cmd_dispatch_running(const MixaCmdDispatch * d);
void mixa_cmd_dispatch_release(MixaCmdDispatch * d);
#endif
