/* generated by l1trans from mixa_manager/mixa_cmdline.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fcmdline_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fcmdline_2Eh_2Elm1

#include <stddef.h>
#define MIXA_CMDLINE_OK 0
#define MIXA_CMDLINE_ERR_ARG 1
#define MIXA_CMDLINE_ERR_NOMEM 2
typedef struct MixaCmdLineFaultVTable MixaCmdLineFaultVTable;
typedef struct MixaCmdLine MixaCmdLine;

typedef int (*MixaCmdLineFaultFn)(void * ctx, size_t requested_size);

struct MixaCmdLineFaultVTable {
    MixaCmdLineFaultFn on_alloc;
    void * ctx;
};

struct MixaCmdLine {
    unsigned * cps;
    size_t len;
    size_t cap;
    size_t cursor;
};

void mixa_cmdline_init(MixaCmdLine * cl);
void mixa_cmdline_release(MixaCmdLine * cl);
int mixa_cmdline_insert(MixaCmdLine * cl, const MixaCmdLineFaultVTable * fault, unsigned codepoint);
void mixa_cmdline_backspace(MixaCmdLine * cl);
void mixa_cmdline_delete_forward(MixaCmdLine * cl);
void mixa_cmdline_move_left(MixaCmdLine * cl);
void mixa_cmdline_move_right(MixaCmdLine * cl);
void mixa_cmdline_move_home(MixaCmdLine * cl);
void mixa_cmdline_move_end(MixaCmdLine * cl);
void mixa_cmdline_clear(MixaCmdLine * cl);
int mixa_cmdline_extract_to_cursor_utf8(const MixaCmdLine * cl, const MixaCmdLineFaultVTable * fault, char ** out);
int mixa_cmdline_char_position(size_t start_row, size_t start_col, size_t screen_cols, size_t screen_rows, size_t index, size_t len, size_t * out_row, size_t * out_col);
#endif
