/* generated by l1trans from mixa_manager/mixa_core.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fcore_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fcore_2Eh_2Elm1

#include <stddef.h>
typedef unsigned char MixaCellByte;
typedef struct MixaCell MixaCell;
typedef struct MixaTextRect MixaTextRect;

typedef enum MixaStyle {
    MIXA_STYLE_BOLD = 1,
    MIXA_STYLE_UNDERLINE = 2,
    MIXA_STYLE_REVERSE = 4
} MixaStyle;

struct MixaCell {
    unsigned codepoint;
    MixaCellByte fg;
    MixaCellByte bg;
    MixaCellByte flags;
    MixaCellByte width;
    MixaCellByte alpha;
};

struct MixaTextRect {
    size_t rows;
    size_t cols;
    MixaCell * cells;
};

#endif
