/* generated by l1trans from mixa_manager/mixa_pointer.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fpointer_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fpointer_2Eh_2Elm1

#include <stddef.h>
#include <stdint.h>
#define MIXA_POINTER_OK 0
#define MIXA_POINTER_ERR 1
#define MIXA_POINTER_UP 0
#define MIXA_POINTER_UP_RIGHT 1
#define MIXA_POINTER_RIGHT 2
#define MIXA_POINTER_DOWN_RIGHT 3
#define MIXA_POINTER_DOWN 4
#define MIXA_POINTER_DOWN_LEFT 5
#define MIXA_POINTER_LEFT 6
#define MIXA_POINTER_UP_LEFT 7
#define MIXA_POINTER_CP_UP 0x2B06U
#define MIXA_POINTER_CP_UP_RIGHT 0x2B08U
#define MIXA_POINTER_CP_RIGHT 0x2B95U
#define MIXA_POINTER_CP_DOWN_RIGHT 0x2B0AU
#define MIXA_POINTER_CP_DOWN 0x2B07U
#define MIXA_POINTER_CP_DOWN_LEFT 0x2B0BU
#define MIXA_POINTER_CP_LEFT 0x2B05U
#define MIXA_POINTER_CP_UP_LEFT 0x2B09U
typedef struct MixaPointer MixaPointer;

struct MixaPointer {
    int is_open;
    int octant;
    size_t row;
    size_t col;
};

int mixa_pointer_init(MixaPointer * p);
void mixa_pointer_release(MixaPointer * p);
unsigned mixa_pointer_codepoint(const MixaPointer * p);
unsigned mixa_pointer_codepoint_for_octant(int octant);
int mixa_pointer_octant_from_delta(int32_t dx, int32_t dy, int prev_octant);
int mixa_pointer_nudge(MixaPointer * p, int32_t dx, int32_t dy);
int mixa_pointer_move_to(MixaPointer * p, size_t row, size_t col);
#endif
