/* generated by l1trans from mixa_manager/mixa_file.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Ffile_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Ffile_2Eh_2Elm1

#include <stddef.h>
#define MIXA_FILE_MODE_READ 1
#define MIXA_FILE_MODE_APPEND 2
#define MIXA_FILE_OK 0
#define MIXA_FILE_ERR_ARG 1
#define MIXA_FILE_ERR_MISSING 2
#define MIXA_FILE_ERR_IO 3
#define MIXA_FILE_ERR_NOMEM 4
typedef struct MixaFile MixaFile;

int mixa_file_open(MixaFile ** out, const char * path_utf8, int mode);
void mixa_file_close(MixaFile * f);
int mixa_file_append(MixaFile * f, const void * buf, size_t n, size_t * wrote);
int mixa_file_read(MixaFile * f, void * buf, size_t n, size_t * got);
int mixa_file_seek(MixaFile * f, size_t abs_off);
int mixa_file_size(MixaFile * f, size_t * out);
#endif
