/* generated by l1trans from mixa_manager/mixa_backend.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fbackend_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fbackend_2Eh_2Elm1

#include <stddef.h>
#include "mixa_manager/mixa_overlay.lm1.h"
#include "mixa_manager/mixa_backend_tableref.h"
typedef struct MixaBackend MixaBackend;
typedef struct MixaEvent MixaEvent;
typedef struct MixaCellMetrics MixaCellMetrics;
typedef struct MixaGlyph MixaGlyph;
typedef struct MixaBackendVTable MixaBackendVTable;
typedef struct MixaBackend MixaBackend;

typedef enum MixaEventKind {
    MIXA_EVENT_NONE = 0,
    MIXA_EVENT_KEY = 1,
    MIXA_EVENT_MOUSE = 2,
    MIXA_EVENT_RESIZE = 3,
    MIXA_EVENT_CLOSE = 4,
    MIXA_EVENT_MOUSE_WHEEL = 5
} MixaEventKind;

typedef enum MixaKeyCode {
    MIXA_KEY_NONE = 0,
    MIXA_KEY_UP = 1,
    MIXA_KEY_DOWN = 2,
    MIXA_KEY_LEFT = 3,
    MIXA_KEY_RIGHT = 4,
    MIXA_KEY_HOME = 5,
    MIXA_KEY_END = 6,
    MIXA_KEY_PAGE_UP = 7,
    MIXA_KEY_PAGE_DOWN = 8,
    MIXA_KEY_INSERT = 9,
    MIXA_KEY_DELETE = 10,
    MIXA_KEY_BACKSPACE = 11,
    MIXA_KEY_TAB = 12,
    MIXA_KEY_ENTER = 13,
    MIXA_KEY_ESCAPE = 14,
    MIXA_KEY_F1 = 15,
    MIXA_KEY_F2 = 16,
    MIXA_KEY_F3 = 17,
    MIXA_KEY_F4 = 18,
    MIXA_KEY_F5 = 19,
    MIXA_KEY_F6 = 20,
    MIXA_KEY_F7 = 21,
    MIXA_KEY_F8 = 22,
    MIXA_KEY_F9 = 23,
    MIXA_KEY_F10 = 24,
    MIXA_KEY_F11 = 25,
    MIXA_KEY_F12 = 26
} MixaKeyCode;

typedef enum MixaModifier {
    MIXA_MOD_SHIFT = 1,
    MIXA_MOD_CTRL = 2,
    MIXA_MOD_ALT = 4,
    MIXA_MOD_META = 8
} MixaModifier;

typedef enum MixaMouseButton {
    MIXA_BUTTON_LEFT = 1,
    MIXA_BUTTON_MIDDLE = 2,
    MIXA_BUTTON_RIGHT = 4
} MixaMouseButton;

typedef enum MixaGlyphLayer {
    MIXA_LAYER_TEXT = 0,
    MIXA_LAYER_UPPER = 1,
    MIXA_LAYER_POINTER = 2
} MixaGlyphLayer;

struct MixaEvent {
    int kind;
    unsigned codepoint;
    int keycode;
    unsigned modifiers;
    size_t row;
    size_t col;
    unsigned buttons;
    size_t cols;
    size_t rows;
    int wheel_delta;
};

struct MixaCellMetrics {
    size_t text_cell_width;
    size_t text_cell_height;
    size_t upper_cell_width;
    size_t upper_cell_height;
    size_t pointer_cell_width;
    size_t pointer_cell_height;
};

struct MixaGlyph {
    size_t width;
    size_t height;
    int bearing_x;
    int bearing_y;
    size_t advance;
    const MixaU8 * coverage;
    int missing;
};

typedef int (*MixaBackendOpenFn)(MixaBackend ** out, size_t cols, size_t rows, MixaCellMetrics * metrics);

typedef int (*MixaBackendPresentFn)(MixaBackend * backend, const MixaU8 * rgba, size_t bytes);

typedef int (*MixaBackendPollFn)(MixaBackend * backend, MixaEvent * out);

typedef size_t (*MixaBackendClipboardGetFn)(const MixaBackend * backend, char * out, size_t cap);

typedef int (*MixaBackendClipboardSetFn)(MixaBackend * backend, const char * text);

typedef int (*MixaBackendGlyphFn)(MixaBackend * backend, int layer, unsigned codepoint, MixaGlyph * out);

typedef void (*MixaBackendCloseFn)(MixaBackend * backend);

struct MixaBackendVTable {
    const char * name;
    MixaBackendOpenFn open;
    MixaBackendPresentFn present;
    MixaBackendPollFn poll;
    MixaBackendClipboardGetFn clipboard_get;
    MixaBackendClipboardSetFn clipboard_set;
    MixaBackendGlyphFn glyph;
    MixaBackendCloseFn close;
};

struct MixaBackend {
    const MixaBackendVTable * vt;
};

int mixa_backend_open(const MixaBackendVTable * vt, MixaBackend ** out, size_t cols, size_t rows, MixaCellMetrics * metrics);
int mixa_backend_present(MixaBackend * backend, const MixaU8 * rgba, size_t bytes);
int mixa_backend_poll(MixaBackend * backend, MixaEvent * out);
size_t mixa_backend_clipboard_get(const MixaBackend * backend, char * out, size_t cap);
int mixa_backend_clipboard_set(MixaBackend * backend, const char * text);
void mixa_backend_close(MixaBackend * backend);
int mixa_backend_glyph(MixaBackend * backend, int layer, unsigned codepoint, MixaGlyph * out);
int mixa_backend_table_valid(const MixaBackendVTable * vt);
#endif
