/* generated by l1trans from mixa_manager/mixa_cmdline_dispatch_impl.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fcmdline_5Fdispatch_5Fimpl_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fcmdline_5Fdispatch_5Fimpl_2Eh_2Elm1

#include "mixa_manager/mixa_cmdline_dispatch.lm1.h"
#include "mixa_manager/mixa_process.lm1.h"
#include "mixa_manager/mixa_file.lm1.h"
#include <stddef.h>
typedef struct MixaProcessMarkerScanner MixaProcessMarkerScanner;
typedef struct MixaCmdDispatch MixaCmdDispatch;

#endif
