/* generated by l1trans from mixa_manager/mixa_highlight.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fhighlight_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fhighlight_2Eh_2Elm1

#include <stddef.h>
#include "mixa_manager/mixa_core.lm1.h"
typedef struct MixaHighlight MixaHighlight;

struct MixaHighlight {
    int is_open;
    int is_active;
    size_t row;
    size_t col;
    size_t nrows;
    size_t ncols;
    unsigned fg;
    MixaCell * saved;
    size_t saved_count;
    size_t saved_cap;
    MixaTextRect * target_rect;
    MixaCell * target_cells;
    size_t target_rows;
    size_t target_cols;
};

int mixa_highlight_init(MixaHighlight * hl);
void mixa_highlight_release(MixaHighlight * hl);
int mixa_highlight_set(MixaHighlight * hl, MixaTextRect * rect, size_t row, size_t col, size_t nrows, size_t ncols, unsigned fg);
int mixa_highlight_clear(MixaHighlight * hl, MixaTextRect * rect);
#endif
