/* generated by l1trans from mixa_manager/mixa_app_fmpanel_impl.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fapp_5Ffmpanel_5Fimpl_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fapp_5Ffmpanel_5Fimpl_2Eh_2Elm1

#include "mixa_manager/mixa_app_fmpanel.lm1.h"
#include "mixa_manager/mixa_highlight.lm1.h"
#include "mixa_manager/mixa_core.lm1.h"
#include <stddef.h>
#define MIXA_APP_FMPANEL_PATH_MAX 1024
typedef struct MixaAppFmPanel MixaAppFmPanel;

#endif
