/* generated by l1trans from mixa_manager/mixa_overlay.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Foverlay_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Foverlay_2Eh_2Elm1

#include <stddef.h>
typedef unsigned char MixaU8;

void mixa_palette_rgb(unsigned index, MixaU8 * out_r, MixaU8 * out_g, MixaU8 * out_b);
#endif
