/* generated by l1trans from mixa_manager/mixa_buttons.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fbuttons_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fbuttons_2Eh_2Elm1

#include <stddef.h>
#include "mixa_manager/mixa_core.lm1.h"
#include "mixa_manager/mixa_tiles.lm1.h"
#define MIXA_BUTTONS_OK 0
#define MIXA_BUTTONS_ERR 1
#define MIXA_BUTTON_NONE -1
typedef struct MixaButton MixaButton;
typedef struct MixaButtonLine MixaButtonLine;
typedef struct MixaButtonPanel MixaButtonPanel;

struct MixaButton {
    char * label;
    size_t row;
    size_t col;
    size_t nrows;
    size_t ncols;
    unsigned fg;
    unsigned bg;
    unsigned alpha;
    int is_sep;
    int enlarge;
};

struct MixaButtonLine {
    MixaButton * items;
    size_t count;
    size_t cap;
};

struct MixaButtonPanel {
    MixaButtonLine * lines;
    size_t line_count;
    size_t line_cap;
    size_t hb;
    size_t wb;
    size_t margin;
    size_t panel_w;
    size_t panel_h;
    size_t origin_row;
    size_t origin_col;
    size_t view_w;
    size_t scroll_x;
    int is_open;
};

int mixa_button_panel_init(MixaButtonPanel * panel, size_t hb);
void mixa_button_panel_release(MixaButtonPanel * panel);
size_t mixa_button_width(size_t hb, size_t wb, const char * label);
int mixa_button_panel_add(MixaButtonPanel * panel, size_t line, const char * label, unsigned fg, unsigned bg, unsigned alpha);
int mixa_button_panel_add_sep(MixaButtonPanel * panel, size_t line);
int mixa_button_panel_layout(MixaButtonPanel * panel);
int mixa_button_panel_hit(const MixaButtonPanel * panel, size_t cell_row, size_t cell_col);
int mixa_button_panel_draw(const MixaButtonPanel * panel, MixaTextRect * rect);
size_t mixa_button_panel_count(const MixaButtonPanel * panel);
#endif
