/* generated by l1trans from mixa_manager/mixa_help.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fhelp_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fhelp_2Eh_2Elm1

#include <stddef.h>
#include "mixa_manager/mixa_file.lm1.h"
#include "mixa_manager/mixa_backend.lm1.h"
#define MIXA_HELP_OK 0
#define MIXA_HELP_ERR_ARG 1
#define MIXA_HELP_ERR_NOMEM 2
#define MIXA_HELP_ERR_IO 3
#define MIXA_HELP_HIT_NONE 0
#define MIXA_HELP_HIT_ACTION 1
typedef struct MixaHelpCtx MixaHelpCtx;

struct MixaHelpCtx {
    MixaFile * console_file;
    int last_status;
};

const char * mixa_help_text(void);
int mixa_help_action(void * ctx_raw);
int mixa_help_key_event(MixaHelpCtx * ctx, const MixaEvent * ev);
int mixa_help_hit(MixaHelpCtx * ctx, size_t cell_row, size_t cell_col, size_t btn_row, size_t btn_col, size_t btn_nrows, size_t btn_ncols);
#endif
