/* generated by l1trans from mixa_manager/mixa_event_fifo.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fevent_5Ffifo_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fevent_5Ffifo_2Eh_2Elm1

#include <stddef.h>
#include "mixa_manager/mixa_backend.lm1.h"
typedef struct MixaEventFifo MixaEventFifo;

struct MixaEventFifo {
    MixaEvent * items;
    size_t capacity;
    size_t head;
    size_t count;
    int is_open;
};

int mixa_event_fifo_init(MixaEventFifo * fifo);
void mixa_event_fifo_release(MixaEventFifo * fifo);
int mixa_event_fifo_push(MixaEventFifo * fifo, const MixaEvent * ev);
int mixa_event_fifo_pop(MixaEventFifo * fifo, MixaEvent * out);
size_t mixa_event_fifo_count(const MixaEventFifo * fifo);
#endif
