/* generated by l1trans from mixa_manager/mixa_app_controller_impl.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fapp_5Fcontroller_5Fimpl_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fapp_5Fcontroller_5Fimpl_2Eh_2Elm1

#include "mixa_manager/mixa_app_controller.lm1.h"
#include "mixa_manager/mixa_file.lm1.h"
#include "mixa_manager/mixa_help.lm1.h"
#include "mixa_manager/mixa_cmdline.lm1.h"
#include "mixa_manager/mixa_cmdline_dispatch.lm1.h"
#include "mixa_manager/mixa_backend.lm1.h"
#include "mixa_manager/mixa_core.lm1.h"
#include "mixa_manager/mixa_overlay.lm1.h"
#include <stddef.h>
typedef struct MixaAppLoop MixaAppLoop;
typedef struct MixaFmAllocVTable MixaFmAllocVTable;
typedef struct MixaConsoleView MixaConsoleView;
typedef struct MixaConsolePending MixaConsolePending;
typedef struct MixaCopySink MixaCopySink;
typedef struct MixaAppController MixaAppController;

#endif
