/* generated by l1trans from mixa_manager/mixa_app_fmpanel.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fapp_5Ffmpanel_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fapp_5Ffmpanel_2Eh_2Elm1

#include <stddef.h>
#include "mixa_manager/mixa_core.lm1.h"
#define MIXA_APP_FMPANEL_OK 0
#define MIXA_APP_FMPANEL_ERR_ARG 1
#define MIXA_APP_FMPANEL_ERR_NOMEM 2
typedef struct MixaFm MixaFm;
typedef struct MixaAppFmPanel MixaAppFmPanel;

int mixa_app_fmpanel_open(MixaAppFmPanel ** out, MixaFm * fm, size_t list_row, size_t list_col, size_t list_rows, size_t list_cols);
void mixa_app_fmpanel_close(MixaAppFmPanel * p);
int mixa_app_fmpanel_render(MixaAppFmPanel * p, MixaTextRect * rect);
int mixa_app_fmpanel_hit(MixaAppFmPanel * p, MixaTextRect * rect, size_t cell_row, size_t cell_col);
int mixa_app_fmpanel_confirm_is_open(const MixaAppFmPanel * p);
void mixa_app_fmpanel_report_copy_result(MixaAppFmPanel * p, int status);
int mixa_app_fmpanel_key(MixaAppFmPanel * p, int keycode);
int mixa_app_fmpanel_wheel(MixaAppFmPanel * p, size_t cell_row, size_t cell_col, int notches);
int mixa_app_fmpanel_release(MixaAppFmPanel * p);
size_t mixa_app_fmpanel_view_top(const MixaAppFmPanel * p);
int mixa_app_fmpanel_highlight_index(const MixaAppFmPanel * p);
int mixa_app_fmpanel_drag_active(const MixaAppFmPanel * p);
#endif
