/* generated by l1trans from mixa_manager/mixa_pump.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fpump_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fpump_2Eh_2Elm1

#include <stddef.h>
#include "mixa_manager/mixa_backend.lm1.h"
#include "mixa_manager/mixa_event_fifo.lm1.h"
typedef struct MixaPump MixaPump;

struct MixaPump {
    MixaEventFifo inbox;
    int is_open;
};

int mixa_pump_open(MixaPump * pump);
void mixa_pump_release(MixaPump * pump);
int mixa_pump_drain(MixaPump * pump, MixaBackend * backend);
int mixa_pump_next(MixaPump * pump, MixaEvent * out);
size_t mixa_pump_pending(const MixaPump * pump);
#endif
