/* generated by l1trans from mixa_manager/mixa_app_controller.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fapp_5Fcontroller_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fapp_5Fcontroller_2Eh_2Elm1

#include <stddef.h>
#include "mixa_manager/mixa_backend.lm1.h"
#include "mixa_manager/mixa_core.lm1.h"
#define MIXA_APP_CONTROLLER_OK 0
#define MIXA_APP_CONTROLLER_ERR_ARG 1
#define MIXA_APP_CONTROLLER_ERR_OPEN 2
typedef struct MixaAppController MixaAppController;
typedef struct MixaFm MixaFm;
typedef struct MixaAppFmPanel MixaAppFmPanel;

int mixa_app_controller_open(MixaAppController ** out, const MixaBackendVTable * vt, const char * root_utf8);
int mixa_app_controller_step(MixaAppController * c, int * out_had_error);
int mixa_app_controller_running(const MixaAppController * c);
void mixa_app_controller_close(MixaAppController * c);
MixaBackend * mixa_app_controller_backend(const MixaAppController * c);
const MixaTextRect * mixa_app_controller_text_rect(const MixaAppController * c);
const MixaTextRect * mixa_app_controller_upper_rect(const MixaAppController * c);
int mixa_app_controller_command_running(const MixaAppController * c);
int mixa_app_controller_last_exit_code(const MixaAppController * c);
const char * mixa_app_controller_cwd(const MixaAppController * c);
size_t mixa_app_controller_cursor_row(const MixaAppController * c);
size_t mixa_app_controller_cursor_col(const MixaAppController * c);
size_t mixa_app_controller_file_size(const MixaAppController * c);
MixaFm * mixa_app_controller_fm(const MixaAppController * c);
MixaAppFmPanel * mixa_app_controller_fmpanel(const MixaAppController * c);
#endif
