/* generated by l1trans from mixa_manager/mixa_backend_headless.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fbackend_5Fheadless_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fbackend_5Fheadless_2Eh_2Elm1

#include "mixa_manager/mixa_backend.lm1.h"
#include "mixa_manager/mixa_event_fifo.lm1.h"
typedef struct MixaHeadless MixaHeadless;

struct MixaHeadless {
    const MixaBackendVTable * vt;
    int is_open;
    size_t cols;
    size_t rows;
    size_t cell_width;
    size_t cell_height;
    size_t frame_w;
    size_t frame_h;
    size_t frame_bytes;
    MixaU8 * frame;
    char * clipboard;
    size_t clipboard_len;
    MixaEventFifo * inbox;
};

const MixaBackendVTable * mixa_backend_headless_table(void);
int mixa_headless_push_event(MixaBackend * backend, const MixaEvent * ev);
int mixa_headless_frame_at(const MixaBackend * backend, size_t x, size_t y, MixaU8 * out);
#endif
