/* generated by l1trans from mixa_manager/mixa_process_win32.h.lm1 */
#ifndef LM_H_mixa_5Fmanager_2Fmixa_5Fprocess_5Fwin32_2Eh_2Elm1
#define LM_H_mixa_5Fmanager_2Fmixa_5Fprocess_5Fwin32_2Eh_2Elm1

#include "mixa_manager/mixa_process.lm1.h"
#include <stddef.h>
#include "mixa_manager/mixa_file_win32_l2_win.h"
typedef struct MixaProcess MixaProcess;

#endif
